Repository DevNight-CNX/covid-19-cnx, pull requests merged in 2020-03, with the labels that each got.

#1 Chore/setup api endpoint
  .eslintignore
  .github/workflows/check.yml
  src/constants/api-endpoints.js
  src/utils/services/__tests__/fetch.js
  src/utils/services/__tests__/fetchDelete.test.js
  src/utils/services/__tests__/fetchGet.test.js
  src/utils/services/__tests__/fetchPost.test.js
  src/utils/services/__tests__/fetchPut.test.js
Labels: done, waiting for review

#2 update map structure code
  .firebase/hosting.YnVpbGQ.cache
  .gitignore
  src/components/FcmManager.js
  src/pages/Map/OldMap.js
  src/pages/Map/assets/confirmed.svg
  src/pages/Map/assets/pin.svg
  src/pages/Map/assets/ripple.svg
  src/pages/Map/components/InfoPopup/index.js
  src/pages/Map/index.js
  src/pages/Map/mapData.js
  src/pages/Map/mapStyles.js
Labels: done, waiting for review

#3 fetch case for ploting in map
  src/constants/api-endpoints.js
  src/pages/Map/assets/ripple.svg
  src/pages/Map/index.js
  src/services/case.js
  src/utils/useFetch.js
Labels: done, waiting for review

#4 setup deploy firebase and add codeowners
  .github/CODEOWNERS
  .github/workflows/deploy.yml
  env-config.json
Labels: done, waiting for review

#6 change from self host to ubuntu-lastest
  .github/workflows/deploy.yml
Labels: done, waiting for review

#7 use firebase action
  .github/workflows/deploy.yml
Labels: done, waiting for review

#11 set theme component
  src/GlobalStyled.js
  src/styles/color.js
  src/styles/typography.js
Labels: done, waiting for review

#10 implement restriction map and info box
  public/index.html
  src/index.js
  src/pages/Map/components/InfoPopup/index.js
  src/pages/Map/index.js
  src/services/case.js
Labels: done, waiting for review

#13 Feature/button component
  src/components/Button/index.js
Labels: done, waiting for review

#12 implement layout for landing page
  src/Router.js
  src/components/Map/OldMap.js
  src/components/Map/assets/confirmed.svg
  src/components/Map/assets/pin.svg
  src/components/Map/assets/ripple.svg
  src/components/Map/components/InfoPopup/index.js
  src/components/Map/index.js
  src/components/Map/mapStyles.js
  src/constants/api-endpoints.js
  src/pages/Example/pages/Map/index.js
  src/pages/Home/assets/circle.svg
  src/pages/Home/assets/logo.svg
  src/pages/Home/components/Summary/assets/dead.svg
  src/pages/Home/components/Summary/assets/hospital.svg
  src/pages/Home/components/Summary/assets/user.svg
  src/pages/Home/components/Summary/assets/virus.svg
  src/pages/Home/components/Summary/index.js
  src/pages/Home/index.js
  src/pages/Home/index.view.js
  src/pages/Landing/index.js
  src/pages/Map/mapData.js
  src/services/case.js
  src/styles/color.js
Labels: done, waiting for review

#5 Feature/news carousel
  env-config.json
  package.json
  src/constants/api-endpoints.js
  src/pages/Home/index.js
  src/pages/components/news-carousel.js
  src/services/data/index.js
  yarn.lock
Labels: done, waiting for review

#14 Feature/report card
  src/components/Card/dislike.svg
  src/components/Card/index.js
  src/components/Card/like.svg
Labels: done, waiting for review

#15 implements ui field and textarea
  package.json
  src/components/Field/index.view.js
  src/styles/color.js
  yarn.lock
Labels: done, waiting for review

#16 implement field (not implement ui yet)
  package.json
  public/index.html
  src/components/Button/index.js
  src/components/Field/ImageUploader/index.js
  src/components/Field/PlaceAutocomplete/index.js
  src/components/Field/index.js
  src/components/Field/index.view.js
  src/components/UploadImageHandler/index.js
  src/pages/Report/Create/index.js
  src/styles/typography.js
  yarn.lock
Labels: done, waiting for review

#17 Feature/modal warning area
  src/components/Map/assets/Arenaicon.svg
  src/components/Map/index.js
  src/styles/typography.js
Labels: done, waiting for review

#18 News carousel
  package.json
  src/pages/Home/index.js
  src/pages/components/LinkPreView/index.js
  src/pages/components/news-carousel.js
  src/pages/components/newsCarousel.js
  src/services/data/index.js
  yarn.lock
Labels: done, waiting for review

#19 implement authentication with firebase, validate form and integrate with api for create report
  src/components/Auth/AuthRouter/index.js
  src/components/AuthManager.js
  src/components/Field/ImageUploader/index.js
  src/components/useFirebaseAuthen.js
  src/constants/api-endpoints.js
  src/pages/Report/Create/index.js
  src/services/report.js
  src/utils/form/validators/__tests__/index.test.js
  src/utils/form/validators/errorMessage/index.js
  src/utils/form/validators/utils/__tests__/composeValidators.test.js
  src/utils/form/validators/validate/index.js
  src/utils/services/fetch.js
Labels: done

#21 update popup ui
  src/GlobalStyled.js
  src/components/Map/components/InfoPopup/index.js
  src/components/Map/index.js
Labels: done, waiting for review

#22 Feature/section footer
  src/components/Button/index.js
  src/components/Map/index.js
  src/pages/Home/assets/AddNews.svg
  src/pages/Home/index.js
  src/pages/Report/FakeNews/assets/FakeNews.svg
  src/pages/Report/FakeNews/index.js
Labels: done, waiting for review

#23 Chore/update css card
  src/components/Card/assets/dislike.svg
  src/components/Card/assets/like.svg
  src/components/Card/index.js
Labels: done, waiting for review

#24 Feature/bar header
  src/components/BarNavigation/assets/back.svg
  src/components/BarNavigation/assets/close.svg
  src/components/BarNavigation/navigation.js
  src/pages/Report/Create/index.js
  src/styles/color.js
Labels: done, waiting for review

#25 implement render props component for like system
  src/Router.js
  src/components/AuthManager.js
  src/components/LikeManager.js
  src/constants/api-endpoints.js
  src/pages/Example/pages/Like/index.js
  src/services/report.js
Labels: done, waiting for review

#26 implement PWA (add to home screen, favicon)
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/mstile-150x150.png
  src/index.js
Labels: done, waiting for review

#28 Updated home page
  package.json
  src/components/Map/index.js
  src/components/Typography/DynamicComponent.js
  src/components/Typography/index.js
  src/pages/Home/components/News/assets/AddNews.svg
  src/pages/Home/components/News/index.js
  src/pages/Home/components/News/index.view.js
  src/pages/Home/components/Summary/index.js
  src/pages/Home/index.js
  src/pages/Home/index.view.js
  src/pages/Report/FakeNews/index.js
Labels: waiting for review

#29 custom ui selester placse
  src/components/Field/index.view.js
Labels: done, waiting for review

#27 implement toast for showing success/error when user submit report
  .github/CODEOWNERS
  public/index.html
  src/components/Map/OldMap.js
  src/pages/Report/Create/index.js
  src/services/report.js
  src/utils/services/fetch.js
Labels: done, waiting for review

#30 All report
  src/components/Card/assets/location.svg
  src/components/Card/index.js
  src/constants/api-endpoints.js
  src/pages/Report/Full/index.js
  src/services/report.js
Labels: done, waiting for review

#31 implement policy link
  src/Router.js
  src/pages/Policy/index.js
Labels: done, waiting for review, wip

#33 Feature/action like in card
  src/components/Card/assets/actionDislike.svg
  src/components/Card/assets/actionLike.svg
  src/components/Card/index.js
Labels: done, waiting for review

#32 Feature/report detail
  src/components/Card/index.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/index.js
  src/pages/components/newsCarousel.js
  src/services/report.js
  src/styles/color.js
Labels: done, waiting for review

#35 fix submit ui
  src/components/BarNavigation/navigation.js
  src/components/Field/index.view.js
  src/pages/Report/Create/index.js
Labels: done, waiting for review

#36 remove image section
  src/pages/Report/Detail/index.js
  src/pages/components/LinkPreView/index.js
  src/pages/components/newsCarousel.js
Labels: done, waiting for review

#37 Updated back navigation
  src/components/BarNavigation/index.view.js
  src/components/BarNavigation/navigation.js
  src/components/Card/index.js
  src/pages/Report/Create/index.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/index.js
  src/styles/theme.js
  src/styles/typography.js
Labels: waiting for review

#34 implement layout for desktop dashboard
  package.json
  src/Router.js
  src/components/SubmitReportButton/assets/AddNews.svg
  src/components/SubmitReportButton/index.js
  src/pages/DesktopDashboard/MapAndNews/index.js
  src/pages/DesktopDashboard/ReliableReport/index.js
  src/pages/DesktopDashboard/Report/index.js
  src/pages/DesktopDashboard/components/Paper.js
  src/pages/DesktopDashboard/index.js
  src/pages/Home/components/Header/index.js
  src/pages/Home/components/News/index.js
  src/pages/Home/components/Summary/index.js
  src/pages/Home/index.js
  src/pages/Home/index.view.js
  src/pages/Report/FakeNews/Explanation.js
  src/pages/Report/FakeNews/FakeNewCount.js
  src/pages/Report/FakeNews/assets/fakeNews.svg
  src/pages/Report/FakeNews/index.js
  yarn.lock
Labels: done, waiting for review

#39 New report context and reliable reports
  jsconfig.json
  src/App.js
  src/contexts/report.context.js
  src/pages/Home/components/News/index.js
  src/pages/Home/components/News/index.view.js
  src/pages/Home/index.view.js
  src/pages/Report/Full/index.js
Labels: waiting for review

#41 show item select
  src/components/BarNavigation/index.view.js
  src/components/Field/PlaceAutocomplete/index.js
  src/components/Field/index.view.js
Labels: done, waiting for review

#40 remove unused code
  src/Router.js
  src/pages/Example/List/index.js
  src/pages/Example/Router.js
  src/pages/Example/components/Item/index.js
  src/pages/Example/components/Item/index.stories.js
  src/pages/Example/components/List/index.js
  src/pages/Example/components/List/index.stories.js
  src/pages/Example/components/index.js
  src/pages/Example/index.js
  src/pages/Example/index.view.js
  src/pages/Example/pages/Counter/List/index.js
  src/pages/Example/pages/Counter/List/index.view.js
  src/pages/Example/pages/Counter/index.js
  src/pages/Example/pages/Counter/index.view.js
  src/pages/Example/pages/FinalForm/index.js
  src/pages/Example/pages/FinalForm/index.view.js
  src/pages/Example/pages/Like/index.js
  src/pages/Example/pages/Map/index.js
  src/pages/Example/pages/Todo/AddTodo/index.js
  src/pages/Example/pages/Todo/AddTodo/index.view.js
  src/pages/Example/pages/Todo/Filter/index.js
  src/pages/Example/pages/Todo/Filter/index.view.js
  src/pages/Example/pages/Todo/List/index.js
  src/pages/Example/pages/Todo/List/index.view.js
  src/pages/Example/pages/Todo/index.js
  src/pages/Example/pages/Todo/index.view.js
  src/pages/Example/pages/UserList/index.js
  src/pages/Login.js
Labels: done, waiting for review

#42 fix card text spacing
  src/components/Card/index.js
  src/pages/Report/Detail/index.js
Labels: done, waiting for review

#43 Ploting news in map
  src/App.js
  src/components/Map/assets/news.svg
  src/components/Map/components/InfoPopup/index.js
  src/components/Map/index.js
  src/contexts/news.context.js
  src/pages/components/newsCarousel.js
  src/services/data/index.js
Labels: done, waiting for review

#45 Feature/wait for content load and carousel news
  package.json
  src/components/Card/index.js
  src/components/Card/index.view.js
  src/pages/Home/components/News/index.js
  src/pages/Home/components/News/index.view.js
  src/pages/Home/index.js
  src/pages/Report/Full/index.js
  yarn.lock
Labels: waiting for review

#44 Feature/analytics and logrocket
  package.json
  src/App.js
  src/LogRocketTracking.js
  src/components/Card/index.js
  src/components/LikeManager.js
  src/components/Map/index.js
  src/components/SubmitReportButton/index.js
  src/pages/Report/Create/index.js
  src/pages/components/LinkPreView/index.js
  src/pages/components/newsCarousel.js
  src/utils/eventTracker.js
  yarn.lock
Labels: done, waiting for review

#47 implement counter for fake report
  package.json
  src/contexts/report.context.js
  src/pages/Report/FakeNews/FakeNewCount.js
  yarn.lock
Labels: done, waiting for review

#48 Added linkTo to Button component
  src/components/Button/index.js
  src/pages/Home/components/News/index.js
Labels: done, waiting for review

#49 enable analytics and remove console.log
  src/App.js
  src/pages/Home/components/News/index.js
  src/pages/Report/Create/index.js
Labels: done, waiting for review

#46 implement all report in desktop
  src/Router.js
  src/components/Card/index.js
  src/components/ScrollToTop.js
  src/components/SubmitReportButton/index.js
  src/pages/DesktopDashboard/Report/index.js
  src/pages/DesktopDashboard/components/Paper.js
  src/pages/Home/components/News/index.js
  src/pages/Report/Full/Container.js
  src/pages/Report/Full/index.js
Labels: done, waiting for review

#51 update submit form
  src/services/report.js
  src/utils/services/__tests__/fetch.js
  src/utils/services/fetch.js
Labels: done, waiting for review

#52 fix report date and navigate bar style
  src/components/BarNavigation/navigation.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/Container.js
  src/services/report.js
Labels: done, waiting for review

#50 fix selester show items and reliable
  src/components/Card/index.js
  src/components/Field/PlaceAutocomplete/index.js
  src/components/Field/index.view.js
  src/components/LikeManager.js
Labels: done, waiting for review

#53 Issue/edit card
  src/components/Card/index.js
  src/components/Card/index.view.js
Labels: done, waiting for review

#54 Feature/show address
  src/components/Card/index.js
  src/components/Card/index.view.js
  src/pages/Home/components/News/index.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/Container.js
  src/services/report.js
Labels: done, waiting for review

#55 reverse array and empty state and last update time
  src/components/Card/index.js
  src/components/Card/index.view.js
  src/constants/api-endpoints.js
  src/contexts/report.context.js
  src/pages/DesktopDashboard/index.js
  src/pages/Home/components/Header/index.js
  src/pages/Home/components/News/index.js
  src/pages/Home/components/News/index.view.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/Container.js
  src/services/report.js
  src/services/summary.js
Labels: done, waiting for review

#56 empty state ui
  src/pages/Home/components/News/assets/subtract.svg
  src/pages/Home/components/News/index.view.js
Labels: done, waiting for review

#57 report detail image none fix height
  src/components/Card/index.js
  src/components/Card/index.view.js
Labels: done, waiting for review

#59 preview link image
  src/pages/components/LinkPreView/assets/defaultImage.svg
  src/pages/components/LinkPreView/index.js
  src/pages/components/newsCarousel.js
  src/services/data/index.js
Labels: done, waiting for review

#58 Feature/show reliable news
  src/components/Card/index.js
  src/components/Card/index.view.js
  src/pages/DesktopDashboard/ReliableReport/index.js
  src/pages/Home/components/News/index.js
  src/pages/Home/components/News/index.view.js
  src/pages/Home/components/ReliableReport/assets/subtract.svg
  src/pages/Home/components/ReliableReport/index.js
Labels: done, waiting for review

#60 implement listen firestore for case, news and report
  src/App.js
  src/components/Map/index.js
  src/contexts/news.context.js
  src/contexts/report.context.js
  src/pages/Home/components/News/index.js
  src/utils/useFirestore.js
Labels: done, waiting for review

#61 adjust popup in map and zoom level, update zoom level and remove console.log / unused code
  src/components/AuthManager.js
  src/components/FcmManager.js
  src/components/Map/assets/news.svg
  src/components/Map/components/InfoPopup/index.js
  src/components/Map/index.js
  src/pages/Home/components/Header/index.js
  src/utils/useFirestore.js
Labels: done, waiting for review

#62 Feature/show infected person
  src/pages/DesktopDashboard/MapAndNews/index.js
  src/pages/Home/components/News/index.js
  src/pages/Home/components/Summary/index.js
  src/pages/Home/index.js
  src/pages/Home/index.view.js
Labels: done, waiting for review

#63 implement icon detail
  src/components/Map/components/IconDetail.js
  src/components/Map/index.js
  src/pages/DesktopDashboard/components/Paper.js
Labels: done, waiting for review

#67 fixes safari show blank page
  src/pages/Home/components/Header/index.js
  src/pages/Report/FakeNews/Explanation.js
Labels: done, waiting for review

#66 anonymous report
  src/components/Card/index.js
  src/components/Field/index.js
  src/pages/Report/Create/index.js
  src/services/report.js
Labels: done, waiting for review

#68 add link to counter page
  src/pages/Landing/index.js
Labels: done, waiting for review

#69 fixes icon not show in news carousel
  src/contexts/news.context.js
Labels: done, waiting for review

#70 fake news modal
  src/components/Map/index.js
  src/components/Modal/index.js
  src/pages/Report/FakeNews/FakeNewCount.js
Labels: done, waiting for review

#71 Feature/fix navigation bar redirect
  src/pages/Report/Create/index.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/index.js
Labels: done, waiting for review

#75 loading during fetching data
  src/components/Field/PlaceAutocomplete/index.js
  src/components/Field/index.view.js
  src/pages/Report/FakeNews/FakeNewCount.js
Labels: done, waiting for review

#73 update header spacing, remove พื้นที่เสี่ยง, adjust icon detail
  src/components/Map/components/IconDetail.js
  src/components/Map/index.js
  src/pages/Home/index.view.js
  src/styles/typography.js
Labels: done, waiting for review

#74 edit summary section, news carousel and explanation
  src/pages/Home/components/Summary/index.js
  src/pages/Report/FakeNews/Explanation.js
  src/pages/components/LinkPreView/index.js
Labels: done, waiting for review

#77 fix report detail redirect and fix autocomplete loading
  src/components/Field/index.view.js
  src/contexts/report.context.js
  src/pages/Report/Detail/index.js
Labels: done, waiting for review

#78 fix background color image preview
  src/components/Field/ImageUploader/index.js
Labels: done, waiting for review

#79 Issue/set border redius card
  src/pages/DesktopDashboard/ReliableReport/index.js
  src/pages/DesktopDashboard/components/Paper.js
  src/pages/Home/components/ReliableReport/index.js
  src/pages/Report/FakeNews/FakeNewCount.js
Labels: done, waiting for review

#80 Issue/padding report loading
  src/pages/Home/components/News/index.js
  src/pages/Report/Full/Container.js
Labels: done, waiting for review

#81 lock navigate bar
  src/components/BarNavigation/index.view.js
  src/pages/Report/Create/index.js
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/index.js
Labels: done, waiting for review

#82 fix scroller in all report
  src/components/Card/index.view.js
Labels: done, waiting for review

#76 adding meta social sharing
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/mstile-150x150.png
Labels: done, waiting for review

#83 fix detaill report
  src/pages/Report/Detail/index.js
  src/pages/Report/Full/index.js
Labels: done, waiting for review

#84 implement safe link and update cover
  public/index.html
  src/components/Card/index.js
Labels: done, waiting for review

#85 fix margin
  src/components/Card/index.view.js
Labels: done, waiting for review

#87 test logrocket error
  src/Router.js
  src/pages/DesktopDashboard/pageError.js
Labels: done, waiting for review

#88 fixes text overflow
  src/pages/components/LinkPreView/index.js
Labels: done, waiting for review

#89 edit touchscreen move map
  src/components/Map/index.js
Labels: done, waiting for review

#90 remove error page
  src/Router.js
  src/pages/DesktopDashboard/pageError.js
Labels: done, waiting for review

#91 reliable report order
  src/pages/Home/components/ReliableReport/index.js
Labels: done, waiting for review

#86 setup release (merge ตอน 1 ทุ่มครึ่ง)
  src/Router.js
  src/contexts/report.context.js
  src/pages/Report/Create/index.js
  src/pages/Report/FakeNews/FakeNewCount.js
  src/pages/Report/Full/index.js
Labels: done, waiting for review

#93 update text
  src/pages/Home/components/ReliableReport/index.js
Labels: done, waiting for review

#94 fixes bug from log rocket
  src/components/Card/index.js
  src/contexts/report.context.js
Labels: done, waiting for review

#95 update email in notice
  src/pages/Report/FakeNews/Explanation.js
Labels: done, waiting for review

#96 update text
  src/pages/Report/FakeNews/Explanation.js
Labels: done, waiting for review

#97 remove margin full report
  src/pages/Report/Full/index.js
Labels: done, waiting for review

#98 fixes bug news and cases empty lat/lng
  src/components/Card/index.view.js
  src/components/Map/index.js
  src/contexts/news.context.js
Labels: done, waiting for review

#99 implement popup for hospital
  src/GlobalStyled.js
  src/components/Map/assets/hospital.svg
  src/components/Map/components/CasePopup/assets/pin.svg
  src/components/Map/components/CasePopup/index.js
  src/components/Map/components/IconDetail.js
  src/components/Map/components/NewsPopup/index.js
  src/components/Map/index.js
Labels: done, waiting for review

#100 switch show sections summary
  src/constants/api-endpoints.js
  src/pages/Home/components/Summary/index.js
  src/pages/Home/index.js
  src/pages/Home/index.view.js
  src/services/case.js
  src/utils/useFetch.js
Labels: done, waiting for review

#102 get data summarys constants thailand and cnx
  src/App.js
  src/contexts/summarys.context.js
  src/pages/Home/components/Summary/index.js
Labels: done, waiting for review

#101 implement situation news ui
  src/Router.js
  src/pages/Home/index.js
  src/pages/Home/index.view.js
  src/pages/Report/Situation/index.js
  src/pages/Report/Situation/index.view.js
  src/pages/components/LinkPreView/index.js
  src/pages/components/newsCarousel.js
Labels: done, waiting for review

#103 [Desktop] show toggle summary
  src/pages/DesktopDashboard/MapAndNews/index.js
  src/pages/Home/components/Summary/index.js
Labels: done, waiting for review

#104 implement redesign form and pin map
  src/components/BarNavigation/index.view.js
  src/components/Card/index.js
  src/components/Card/index.view.js
  src/components/Field/ImageUploader/index.js
  src/components/Field/index.js
  src/components/Map/assets/ripple.gif
  src/components/Map/assets/ripple.svg
  src/components/Map/components/CasePopup/index.js
  src/components/Map/components/IconDetail.js
  src/components/Map/components/NewsPopup/assets/pin.svg
  src/components/Map/components/NewsPopup/index.js
  src/components/Map/index.js
  src/pages/Report/Create/assets/news.png
  src/pages/Report/Create/assets/risk.png
  src/pages/Report/Create/index.js
  src/services/report.js
  src/utils/form/validators/validate/index.js
  src/utils/getSafeLink.js
Labels: done, waiting for review

#106 implement loading state of news
  src/pages/DesktopDashboard/MapAndNews/index.js
  src/pages/Home/index.js
  src/pages/components/newsCarousel.js
Labels: done, waiting for review

#107 edit show url report and change variable
  src/components/Card/index.js
  src/contexts/summarys.context.js
  src/pages/DesktopDashboard/MapAndNews/index.js
  src/pages/Home/components/Summary/index.js
  src/pages/Home/index.js
Labels: done, waiting for review

#108 update icon detail
  src/components/Map/components/IconDetail.js
Labels: done, waiting for review

#109 refactor map
  src/components/Map/index.js
Labels: done, waiting for review

#110 install lib url-polyfill fix not support safari ios < 13.0
  package.json
  src/components/Card/index.js
  src/contexts/replaceurl.js
  src/index.js
  yarn.lock
Labels: done, waiting for review

#112 hot fix
  src/contexts/replaceurl.js
Labels: done, waiting for review

#113 add try catch for new URL
  src/contexts/replaceurl.js
Labels: done, waiting for review

#114 update news desktop ui
  src/Router.js
  src/pages/DesktopDashboard/MapAndNews/index.js
  src/pages/DesktopDashboard/News/index.js
  src/pages/DesktopDashboard/index.js
  src/pages/Home/index.js
  src/pages/News/index.js
  src/pages/News/index.view.js
  src/pages/components/newsList.js
Labels: done, waiting for review

#111 update pin ui
  src/App.js
  src/components/Map/components/CasePopup/index.js
Labels: done, waiting for review

#115 Feature/new popup ui
  src/components/Map/components/CasePopup/index.js
  src/components/Map/components/NewsPopup/index.js
  src/components/Map/components/ScreeningPointPopup/index.js
  src/components/Map/index.js
  src/pages/Report/Create/index.js
Labels: done, waiting for review

#116 implement scroll into view for report detail (desktop)
  src/pages/DesktopDashboard/Report/index.js
Labels: done

#117 fix news
  src/contexts/news.context.js
  src/pages/DesktopDashboard/News/index.js
  src/pages/News/index.js
Labels: done, waiting for review

#120 fixes bug pin not show in map realtime
  src/contexts/summarys.context.js
  src/services/report.js
Labels: done, waiting for review

#121 setup deploy develop
  .firebaserc
  .github/workflows/deploy.yml
Labels: done, waiting for review

#122 use specified firebase config based on environment
  .eslintignore
  .gitignore
  env-config.json
  firebase-messaging-sw.js
  generate-env
  package.json
  src/App.js
Labels: done, waiting for review
